[theme]
primaryColor = "#E8A427"
backgroundColor = "#0F0F0F"
secondaryBackgroundColor = "#1C1C1C"
textColor = "#F0F0F0"
font = "sans serif"

[server]
maxUploadSize = 10

[browser]
gatherUsageStats = false
